image: Visual Studio 2017

# Versioning
version: '1.0.{build}'

assembly_info:
  patch: true
  file: 'src\Common\AzureADWindowsAuthenticator\Properties\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

dotnet_csproj:
  patch: true
  file: 'src\Directory.Build.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# Install
install:
  - ps: scripts\DisableStrongName.ps1

# Build
configuration:
  - Release

build_script:
  - ps: scripts\Build.ps1 -Configuration $(configuration) -Pack -AppVeyorLogger

before_build:
  - ps: scripts\RestorePackages.ps1

# Artifacts
artifacts:
  - path: 'PkgOut\*.nupkg'

# Test
test:
  assemblies:
    only:
      - '**\*.Test.dll'

  categories:
    except:
      - Interactive