image: Visual Studio 2017

# Versioning
version: '1.0.{build}'

init:
  - ps: $env:nugetVersion = "$($env:APPVEYOR_BUILD_VERSION)"
  - ps: if($env:APPVEYOR_REPO_BRANCH -ne 'release') { $env:nugetVersion = "$($env:nugetVersion)-beta"}

assembly_info:
  patch: true
  file: 'src\Common\AzureADWindowsAuthenticator\Properties\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

dotnet_csproj:
  patch: true
  file: 'src\Directory.Build.props'
  version: '{version}'
  package_version: '$(nugetVersion)'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# Install
install:
  - ps: scripts\DisableStrongName.ps1

# Build
build_script:
  - ps: scripts\Build.ps1 -Configuration Release -Pack -AppVeyorLogger

before_build:
  - ps: scripts\RestorePackages.ps1

# Artifacts
artifacts:
  - path: 'PkgOut\*.nupkg'

# Test
test_script:
  - ps: scripts\Test.ps1 -Configuration Release -UploadResultsToAppVeyor